/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.SerializationManager;
import model.Customer;
import model.Invoice;
import model.Item;

/**
 *
 * @author uzivatel
 */
public class MainScreen extends javax.swing.JFrame {

    ArrayList<Customer> customers;
    ArrayList<Item> items;
    ArrayList<Invoice> invoices;
    
    /**
     * Creates new form mainScreen
     */
    public MainScreen() {
        initComponents();
        customers = SerializationManager.loadCustomers();
        items = SerializationManager.loadItems();
        invoices = SerializationManager.loadInvoices();
        
        refreshCustomerTable();
        refreshItemTable();
        refreshInvoiceTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        invoiceButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        invoicesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        addNewButtonInvoice = new javax.swing.JButton();
        refreshButtonInvoice = new javax.swing.JButton();
        customerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        addNewButtonCustomer = new javax.swing.JButton();
        refreshButtonCustomer = new javax.swing.JButton();
        editSelectedButtonCustomer = new javax.swing.JButton();
        itemPanel = new javax.swing.JPanel();
        editSelectedButtonItem = new javax.swing.JButton();
        refreshButtonItem = new javax.swing.JButton();
        addNewButtonItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemButton.setBackground(new java.awt.Color(51, 51, 255));
        itemButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        itemButton.setForeground(new java.awt.Color(255, 255, 255));
        itemButton.setText("Items");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(itemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 60));

        customerButton.setBackground(new java.awt.Color(51, 51, 255));
        customerButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerButton.setForeground(new java.awt.Color(255, 255, 255));
        customerButton.setText("Customers");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 60));

        invoiceButton.setBackground(new java.awt.Color(51, 51, 255));
        invoiceButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        invoiceButton.setForeground(new java.awt.Color(255, 255, 255));
        invoiceButton.setText("Invoices");
        invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(invoiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 60));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new java.awt.CardLayout());

        invoicesPanel.setBackground(java.awt.Color.green);
        invoicesPanel.setForeground(new java.awt.Color(0, 0, 0));
        invoicesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invoiceTable.setAutoCreateRowSorter(true);
        invoiceTable.setBackground(new java.awt.Color(255, 255, 255));
        invoiceTable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        invoiceTable.setForeground(new java.awt.Color(0, 0, 0));
        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        invoiceTable.setGridColor(new java.awt.Color(0, 0, 0));
        invoiceTable.setRowHeight(35);
        invoiceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(invoiceTable);
        JTableHeader tableHeader3 = invoiceTable.getTableHeader();
        Font headerFont = new Font("Verdana", Font.PLAIN, 24);
        tableHeader3.setFont(headerFont);

        invoicesPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 800, 360));

        addNewButtonInvoice.setBackground(java.awt.Color.blue);
        addNewButtonInvoice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addNewButtonInvoice.setForeground(new java.awt.Color(255, 255, 255));
        addNewButtonInvoice.setText("Add New");
        addNewButtonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonInvoiceActionPerformed(evt);
            }
        });
        invoicesPanel.add(addNewButtonInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 60));

        refreshButtonInvoice.setBackground(java.awt.Color.blue);
        refreshButtonInvoice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshButtonInvoice.setForeground(new java.awt.Color(255, 255, 255));
        refreshButtonInvoice.setText("Refresh");
        refreshButtonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonInvoiceActionPerformed(evt);
            }
        });
        invoicesPanel.add(refreshButtonInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 150, 60));

        mainPanel.add(invoicesPanel, "invoicePanel");

        customerPanel.setBackground(java.awt.Color.green);
        customerPanel.setForeground(new java.awt.Color(0, 0, 0));
        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerTable.setAutoCreateRowSorter(true);
        customerTable.setBackground(new java.awt.Color(255, 255, 255));
        customerTable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        customerTable.setForeground(new java.awt.Color(0, 0, 0));
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.setRowHeight(35);
        customerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(customerTable);
        JTableHeader tableHeader = customerTable.getTableHeader();
        Font headerFont = new Font("Verdana", Font.PLAIN, 24);
        tableHeader.setFont(headerFont);

        customerPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 790, 360));

        addNewButtonCustomer.setBackground(java.awt.Color.blue);
        addNewButtonCustomer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addNewButtonCustomer.setForeground(java.awt.Color.white);
        addNewButtonCustomer.setText("Add New");
        addNewButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonCustomerActionPerformed(evt);
            }
        });
        customerPanel.add(addNewButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 60));

        refreshButtonCustomer.setBackground(java.awt.Color.blue);
        refreshButtonCustomer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshButtonCustomer.setForeground(java.awt.Color.white);
        refreshButtonCustomer.setText("Refresh");
        refreshButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonCustomerActionPerformed(evt);
            }
        });
        customerPanel.add(refreshButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 150, 60));

        editSelectedButtonCustomer.setBackground(java.awt.Color.blue);
        editSelectedButtonCustomer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editSelectedButtonCustomer.setForeground(java.awt.Color.white);
        editSelectedButtonCustomer.setText("Edit Selected");
        editSelectedButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectedButtonCustomerActionPerformed(evt);
            }
        });
        customerPanel.add(editSelectedButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 150, 60));

        mainPanel.add(customerPanel, "customerPanel");

        itemPanel.setBackground(java.awt.Color.green);
        itemPanel.setForeground(new java.awt.Color(0, 0, 0));
        itemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editSelectedButtonItem.setBackground(java.awt.Color.blue);
        editSelectedButtonItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editSelectedButtonItem.setForeground(java.awt.Color.white);
        editSelectedButtonItem.setText("Edit Selected");
        editSelectedButtonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectedButtonItemActionPerformed(evt);
            }
        });
        itemPanel.add(editSelectedButtonItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 150, 60));

        refreshButtonItem.setBackground(java.awt.Color.blue);
        refreshButtonItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshButtonItem.setForeground(java.awt.Color.white);
        refreshButtonItem.setText("Refresh");
        refreshButtonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonItemActionPerformed(evt);
            }
        });
        itemPanel.add(refreshButtonItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 150, 60));

        addNewButtonItem.setBackground(java.awt.Color.blue);
        addNewButtonItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addNewButtonItem.setForeground(java.awt.Color.white);
        addNewButtonItem.setText("Add New");
        addNewButtonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonItemActionPerformed(evt);
            }
        });
        itemPanel.add(addNewButtonItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 60));

        itemTable.setAutoCreateRowSorter(true);
        itemTable.setBackground(new java.awt.Color(255, 255, 255));
        itemTable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        itemTable.setForeground(new java.awt.Color(0, 0, 0));
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itemTable.setRowHeight(35);
        itemTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(itemTable);
        JTableHeader itemTableHeader = itemTable.getTableHeader();
        Font headerFont = new Font("Verdana", Font.PLAIN, 24);
        itemTableHeader.setFont(headerFont);

        itemPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 810, 360));

        mainPanel.add(itemPanel, "itemPanel");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 840, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "itemPanel");
    }//GEN-LAST:event_itemButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:                                         
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "customerPanel"); 
    }//GEN-LAST:event_customerButtonActionPerformed

    private void addNewButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonCustomerActionPerformed
        // TODO add your handling code here:
        new CustomerInfoScreen().setVisible(true);
    }//GEN-LAST:event_addNewButtonCustomerActionPerformed

    private void refreshButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonCustomerActionPerformed
        // TODO add your handling code here:
        customers = SerializationManager.loadCustomers();
        refreshCustomerTable();
    }//GEN-LAST:event_refreshButtonCustomerActionPerformed

    private void editSelectedButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectedButtonCustomerActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerTable.getSelectedRow();
        String name = customerTable.getModel().getValueAt(selectedRow, 0).toString();
        String address = customerTable.getModel().getValueAt(selectedRow, 1).toString();
        String city = customerTable.getModel().getValueAt(selectedRow, 2).toString();
        String postcode = customerTable.getModel().getValueAt(selectedRow, 3).toString();
        SerializationManager.deleteCustomer(new Customer(name,address,city,postcode));
        
        CustomerInfoScreen newScreen = new CustomerInfoScreen();
        newScreen.initializeEditMode(name, address, city, postcode);
        newScreen.setVisible(true);
    }//GEN-LAST:event_editSelectedButtonCustomerActionPerformed

    private void editSelectedButtonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectedButtonItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = itemTable.getSelectedRow();
        String name = itemTable.getModel().getValueAt(selectedRow, 0).toString();
        String description = itemTable.getModel().getValueAt(selectedRow, 1).toString();
        String priceAsString = itemTable.getModel().getValueAt(selectedRow, 2).toString();
        double price = Double.parseDouble(priceAsString);
        SerializationManager.deleteItem(new Item(name,description,price));
        
        ItemInfoScreen newScreen = new ItemInfoScreen();
        newScreen.initializeEditMode(name,description,priceAsString);
        newScreen.setVisible(true);
    }//GEN-LAST:event_editSelectedButtonItemActionPerformed

    private void refreshButtonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonItemActionPerformed
        // TODO add your handling code here:
         items = SerializationManager.loadItems();
         refreshItemTable();
    }//GEN-LAST:event_refreshButtonItemActionPerformed

    private void addNewButtonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonItemActionPerformed
        // TODO add your handling code here:
          new ItemInfoScreen().setVisible(true);
    }//GEN-LAST:event_addNewButtonItemActionPerformed

    private void invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "invoicePanel");
    }//GEN-LAST:event_invoiceButtonActionPerformed

    private void addNewButtonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonInvoiceActionPerformed
        // TODO add your handling code here:
        new InvoiceInfoScreen().setVisible(true);
    }//GEN-LAST:event_addNewButtonInvoiceActionPerformed

    private void refreshButtonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonInvoiceActionPerformed
        // TODO add your handling code here:
         invoices = SerializationManager.loadInvoices();
         refreshInvoiceTable();
    }//GEN-LAST:event_refreshButtonInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    
    private void refreshCustomerTable()
    {
        ArrayList<String> columns = new ArrayList<String>();
        ArrayList<String[]> values = new ArrayList<String[]>();
        
        columns.add("Name");
        columns.add("Address");
        columns.add("City");
        columns.add("Postcode");
        
        customers.forEach(i -> {
            values.add(new String[] {i.getName(),i.getAddress(),i.getCity(),i.getPostcode()});
        });
        
        customerTable.setModel(new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray()));
 
    }
    
    private void refreshItemTable()
    {
        ArrayList<String> columns = new ArrayList<String>();
        ArrayList<String[]> values = new ArrayList<String[]>();
        
        columns.add("Name");
        columns.add("Description");
        columns.add("Price");
        
        items.forEach(i -> {
            values.add(new String[] {i.getName(),i.getDescription(),String.valueOf(i.getPrice())});
        });
        
        itemTable.setModel(new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray()));
 
    }
private void refreshInvoiceTable()
    {
        ArrayList<String> columns = new ArrayList<String>();
        ArrayList<String[]> values = new ArrayList<String[]>();
        
        columns.add("Customer");
        columns.add("Date");
        columns.add("Total Price");
        
        invoices.forEach(i -> {
            values.add(new String[] {i.getCustomer().getName(),i.getDate(),String.valueOf(i.getTotalPrice())});
        });
        
        invoiceTable.setModel(new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray()));
 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewButtonCustomer;
    private javax.swing.JButton addNewButtonInvoice;
    private javax.swing.JButton addNewButtonItem;
    private javax.swing.JButton customerButton;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton editSelectedButtonCustomer;
    private javax.swing.JButton editSelectedButtonItem;
    private javax.swing.JButton invoiceButton;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JPanel invoicesPanel;
    private javax.swing.JButton itemButton;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton refreshButtonCustomer;
    private javax.swing.JButton refreshButtonInvoice;
    private javax.swing.JButton refreshButtonItem;
    // End of variables declaration//GEN-END:variables
}