/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.table.JTableHeader;

/**
 *
 * @author uzivatel
 */
public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainScreen
     */
    public mainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemButton = new javax.swing.JButton();
        UserButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        itemPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        UserButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemButton.setBackground(new java.awt.Color(255, 255, 255));
        ItemButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ItemButton.setForeground(new java.awt.Color(0, 0, 0));
        ItemButton.setText("Item");
        ItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 60));

        UserButton.setBackground(new java.awt.Color(255, 255, 255));
        UserButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UserButton.setForeground(new java.awt.Color(0, 0, 0));
        UserButton.setText("User");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 60));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new java.awt.CardLayout());

        itemPanel.setBackground(new java.awt.Color(255, 255, 255));
        itemPanel.setForeground(new java.awt.Color(0, 0, 0));
        itemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 51, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("This is item");
        itemPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 270, 150));

        mainPanel.add(itemPanel, "itemPanel");

        userPanel.setBackground(new java.awt.Color(255, 255, 255));
        userPanel.setForeground(new java.awt.Color(0, 0, 0));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("This is user");
        userPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 270, 150));

        userTable.setBackground(new java.awt.Color(0, 0, 0));
        userTable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.setRowHeight(35);
        jScrollPane1.setViewportView(userTable);
        JTableHeader tableHeader = userTable.getTableHeader();
        Font headerFont = new Font("Verdana", Font.PLAIN, 24);
        tableHeader.setFont(headerFont);

        userPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, 370));

        UserButton1.setBackground(new java.awt.Color(255, 255, 255));
        UserButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UserButton1.setForeground(new java.awt.Color(0, 0, 0));
        UserButton1.setText("Add New");
        UserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButton1ActionPerformed(evt);
            }
        });
        userPanel.add(UserButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 130, 60));

        mainPanel.add(userPanel, "userPanel");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 840, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "itemPanel");
    }//GEN-LAST:event_ItemButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
        // TODO add your handling code here:                                         
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userPanel"); 
    }//GEN-LAST:event_UserButtonActionPerformed

    private void UserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButton1ActionPerformed
        // TODO add your handling code here:
        new userInfoScreen().setVisible(true);
    }//GEN-LAST:event_UserButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ItemButton;
    private javax.swing.JButton UserButton;
    private javax.swing.JButton UserButton1;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
